name: Laravel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 60m  # Timeout vaqtini 60 daqiqagacha oshiramiz
          script: |
            # O'zgaruvchan muhit sozlamalari
            export PATH=$PATH:/usr/local/bin

            # Kerakli katalogga o'tish
            cd /var/www/fitness

            # Git repository ni tekshirish va yangilash
            if [ ! -d .git ]; then
              echo "Git repository topilmadi, yangi clone qilinmoqda..."
              cd ..
              rm -rf fitness
              git clone https://github.com/abdu11aev-samandar/fitness.git fitness
              cd fitness
            else
              git pull origin main
            fi

            # Docker-compose mavjudligini tekshirish va o'rnatish
            if ! command -v docker-compose &> /dev/null; then
              echo "docker-compose o'rnatilmoqda..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Docker Compose orqali ishga tushirish (detach rejimida)
            echo "Eski konteynerlarni to'xtatish..."
            docker-compose down --remove-orphans
            echo "Yangi konteynerlarni ishga tushirish..."
            docker-compose up -d --build

            # Konteynerlar tayyor bo'lishini kutish
            echo "PHP konteynerini ishga tushirish kutilmoqda..."
            attempt=0
            max_attempts=30
            until docker-compose ps | grep php | grep "Up" || [ $attempt -eq $max_attempts ]
            do
              echo "PHP konteynerini kutish: $attempt/$max_attempts"
              sleep 10
              attempt=$((attempt+1))
            done

            if [ $attempt -eq $max_attempts ]; then
              echo "PHP konteyner ishga tushmadi, bajarish davom etmoqda..."
            else
              echo "PHP konteyner ishga tushdi!"
            fi

            # PHP container ichida kerakli buyruqlarni bajarish
            echo "Laravel ilovani sozlash..."
            docker-compose exec -T php bash -c '
              if [ ! -f .env ]; then
                cp .env.example .env
              fi
              composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
              php artisan key:generate
              php artisan migrate --force
              chmod -R 777 storage bootstrap/cache
              php artisan optimize:clear
              php artisan optimize
              php artisan route:cache
            '

            echo "Deployment jarayoni tugadi."
