name: Laravel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/fitness
            git pull origin main

            # Docker Compose orqali ishga tushirish
            docker-compose down --remove-orphans
            docker-compose build --no-cache
            docker-compose up -d

            # Laravel ilovani optimize qilish uchun container ichida buyruqlarni bajarish
            docker-compose exec -T php bash -c "
              php -r "file_exists('.env') || copy('.env.example', '.env')
              composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
              php artisan key:generate
              chmod -R 777 storage bootstrap/cache
              php artisan optimize:clear
              php artisan optimize
              php artisan route:cache
            "
